### ISSUE TITLE
Types DB

### ISSUE THREAD

**Issue by zoolhelmy** [sqrwf/openwrt-collectd-exec-dslstats#4]
I think you need to introduce new variables into /usr/share/collectd/types.db & restart collectd. Otherwise rrd files will not get created.

**Comment by d12r-dev** [comment]
types.db defines _types_ (indicated by the type prefix), not actual _variables_ (although it predefines some common variables with types). Amending types.db is definitely not necessary.

As for restarting collectd, of course you need to restart it, as always when you change anything about its options, but if you change the options through LuCI, it will restart it for you automatically.

**Comment by sqrwf** [comment]
Thank you for your input.

types.db defines variables that can be used as-is, but it also makes them available as _prefixes_ that can be used using the _type-_ prefix (e.g. "errors-near_fec" would map to the "errors" type defined in types.db, in turn mapping to "value:DERIVE:0:U"). Amending types.db is definitely not necessary, and it would be even counterproductive since it is part of the package and would be overwritten with an update.

As for restarting collectd, of course you need to restart it, as always when you change anything about its options. If you change the options through LuCI, it will restart it for you automatically, but if you change them manually you need to restart manually.

**Comment by zoolhelmy** [comment]
Good to know that. It's always good to minimize changes on the package & maintaining sysupgrade.conf entries could potentially missed out any critical update in the future or render the functionality. Thank you.
